### ISSUE TITLE
Grammar railroad diagram

### ISSUE THREAD

**Issue by mingodad** [empirical-soft/empirical-lang#109]
Using this tool https://www.bottlecaps.de/convert/ we can copy and paste https://github.com/empirical-soft/empirical-lang/blob/master/src/Empirical.g4 on the Input grammar: textarea then click the button Convert then after conversion click the button View Diagram to see a nice interactive railroad diagram ( https://en.wikipedia.org/wiki/Syntax_diagram ) that can also be downloaded as xhtml.

Also can be done offline using the java tool https://www.bottlecaps.de/rr/download/rr-1.63-java8.zip (link on the Welcome tab).

**Comment by chrisaycock** [comment]
Thanks for the heads up!
