### ISSUE TITLE
Print a list of a dataframe's columns

### ISSUE THREAD

**Issue by andrewnc** [empirical-soft/empirical-lang#29]
Is there a supported way to list all of the columns of a dataframe?

I am trying to work with data that has more than 6 or so columns so they can't all be printed when I just print the dataframe. 

Any help is appreciated

**Comment by chrisaycock** [comment]
Sadly, not at the moment. I definitely want to add it, so maybe I can bounce a few possible ideas off you in the meantime.

How about something like this?

```
>>> columns(df)
["symbol", "date", "open", "high", "low", "close", "volume"]

>> typeof(df)
!{symbol: String, date: Date, open: Float64, high: Float64, low: Float64, close: Float64, volume: Int64}
```

**Comment by andrewnc** [comment]
Yes, those look great. It might be interesting to also expose a member that contains the columns. Because often times you are working with things like `df.row1` etc. It would be ergonomically nice if you could also ask `df.get_columns` or something along those lines too. 

ps. I've had a really good time with Empirical so far, great work.

**Comment by chrisaycock** [comment]
By the way, if you expand your terminal window, Empirical will automatically resize the Dataframe during printing. So if your window's small size causes Empirical to truncate the output, just increase the window size and rerun your command.

**Comment by andrewnc** [comment]
Definitely, I've tried that. The data frame I'm working with has something like 50+ columns, so that still causes some truncation. 

My work around has been to just run `head file.csv` in another terminal window. :)

**Comment by chrisaycock** [comment]
Regarding member functions or member attributes: I've avoided those so far because my big fear is that the user will have a column name that conflicts with an attribute I've created.

This happened in pandas where `size` became an attribute over time. My backtester had used `trades.size` for years to refer to the `size` column. One day following a system-wide upgrade to the latest version of pandas, all the backtests crashed. I had to rename everything to `trades["size"]`.

Every summer afterwards I had to debug the interns' code with that exact same error.

An alternative is to use a different symbol instead of `.` to indicate compile-time attributes. I've been using `$` to indicate metaprogramming, so something like `df$columns` or `df.$columns`.

**Comment by andrewnc** [comment]
That is a great point. I like the metaprogramming aspect, but wonder if that will feel tacked on as opposed to simply having a built in function?  Either way, I look forward to it. 

Also, as a side note, I am probably going to be writing some quality of life functions (the beginnings of a personal standard library) in Empirical. Would you want me to send those over at some point?

**Comment by chrisaycock** [comment]
Some languages will automatically convert `x.foo()` to `foo(x)` if there is no attribute. I've been thinking about that for Empirical, but again I don't want to run into the `trades.size` conflict.

The analog in some functional languages is infix notation. Haskell uses backticks to force infix:

```
Prelude> let foo x y = x + y
Prelude> 1 `foo` 2
3
```

q/kdb+ will infix a function automatically if it's in the `.q` namespace:

```
q).q.foo:{x+y}
q)1 foo 2
3
```

Either way, the user has given notation to explicitly compel the infixing. I like that idea for attributes, where I force the user to be explicit about what the member (`.`) refers to. I've never seen that in another language, so I'm sure it may confuse users at first. And I've followed the view of "don't do something that isn't common to the user unless it's truly better".

I'll gladly take any code you have. You can either post it on GitHub or email me (christopher.aycock /AT/ empirical-soft.com).

**Comment by chrisaycock** [comment]
This has now been [released](https://www.empirical-soft.com/download.html).

```
>>> let prices = load$("prices.csv")

>>> type_of(prices)
!Provider$prices.csv

>>> columns(prices)
symbol: String
date: Date
open: Float64
high: Float64
low: Float64
close: Float64
volume: Int64 
```
