### ISSUE TITLE
Segmentation fault on nested sort and select

### ISSUE THREAD

**Issue by andrewnc** [empirical-soft/empirical-lang#30]
I ran into a fascinating little edge case. 

`>>> from (sort p by monthly_price) select host_name`
`zsh: segmentation fault  /<user_dir>/empirical`

It works just fine if I assign a temporary result from the sort operation, and then run the selection.

**Comment by chrisaycock** [comment]
Hmm, thanks for showing me this. I'll take a look.

**Comment by chrisaycock** [comment]
Alright, this has been [released](https://www.empirical-soft.com/download.html). Thanks again for the bug report.
